export const clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
export function progressFor(startX,x,width,direction){return clamp((startX-x)*direction/(width*2));}
export function shouldComplete(progress){return progress>0.5;}
/** Renderer is injected: the engine never knows page IDs, content or design. */
export class FlipEngine{
 constructor(book,{render,spreadCount,onChange}){this.book=book;this.render=render;this.count=spreadCount;this.onChange=onChange;this.spread=0;this.layer=book.querySelector('#turn-layer');this.left=book.querySelector('#left');this.right=book.querySelector('#right');this.motion=matchMedia('(prefers-reduced-motion: reduce)');this.draw();book.addEventListener('pointerdown',e=>this.down(e));book.addEventListener('pointermove',e=>this.move(e));book.addEventListener('pointerup',e=>this.up(e));book.addEventListener('pointercancel',()=>this.cancel());book.addEventListener('lostpointercapture',()=>{if(this.drag&&!this.animating)this.cancel();});book.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();this.turn(e.key==='ArrowRight'?1:-1);}});this.resize=new ResizeObserver(()=>{if(this.drag)this.cancel(true);});this.resize.observe(book);}
 draw(){this.left.innerHTML=this.render(this.spread*2);this.right.innerHTML=this.render(this.spread*2+1);this.onChange?.(this.spread);}
 valid(d){return this.spread+d>=0&&this.spread+d<this.count;}
 begin(d){if(this.drag||!this.valid(d))return false;const r=this.book.getBoundingClientRect();this.drag={d,p:0,width:r.width/2,y:0};this.book.classList.add('turning');const front=this.render(this.spread*2+(d===1?1:0));const back=this.render((this.spread+d)*2+(d===1?0:1));if(d===1)this.right.innerHTML=this.render((this.spread+1)*2+1);else this.left.innerHTML=this.render((this.spread-1)*2);this.layer.replaceChildren();this.strips=[];for(let i=0;i<20;i++){const strip=document.createElement('div');strip.className='leaf-strip';strip.style.width=`${r.width/40+0.65}px`;strip.innerHTML=`<div class="leaf-face front"><div class="leaf-content">${front}</div></div><div class="leaf-face back"><div class="leaf-content">${back}</div></div>`;const offset=d===1?i:19-i;strip.querySelector('.front .leaf-content').style.left=`${-offset*r.width/40}px`;strip.querySelector('.back .leaf-content').style.left=`${-(19-offset)*r.width/40}px`;strip.querySelectorAll('.leaf-content').forEach(el=>el.style.width=`${r.width/2}px`);this.layer.append(strip);this.strips.push(strip);}this.paint(0);return true;}
 down(e){if(e.button!==0||this.animating||e.target.closest('a,button,input'))return;const r=this.book.getBoundingClientRect();const d=e.clientX>=r.left+r.width/2?1:-1;if(!this.begin(d))return;e.preventDefault();this.book.focus({preventScroll:true});this.drag.radius=Math.max(12,Math.abs(e.clientX-(r.left+r.width/2)));this.drag.startX=e.clientX;this.drag.startY=e.clientY;this.drag.id=e.pointerId;this.book.setPointerCapture(e.pointerId);}
 move(e){if(!this.drag||this.animating||e.pointerId!==this.drag.id)return;this.drag.y=clamp((e.clientY-this.drag.startY)/this.book.clientHeight,-.3,.3);this.paint(progressFor(this.drag.startX,e.clientX,this.drag.radius,this.drag.d));}
 paint(p){if(!this.drag)return;this.drag.p=p;const {d,width,y}=this.drag;const angle=Math.acos(1-2*p);let x=0,z=0;const w=width/20;for(let i=0;i<20;i++){const bend=Math.sin(Math.PI*p)*.34*Math.sin((i/19-.5)*Math.PI);const a=angle+bend;const strip=this.strips[i];const xx=d===1?x:-x-w*Math.cos(a);const zz=d===1?z:z+w*Math.sin(a);strip.style.transform=`translate3d(${xx}px,${Math.sin(Math.PI*p)*y*i*1.5}px,${zz+2}px) rotateY(${d===1?-a:a}rad)`;strip.style.setProperty('--shade',.16*Math.sin(a));x+=w*Math.cos(a);z+=w*Math.sin(a);}this.book.style.setProperty('--turn-shadow',Math.sin(Math.PI*p)*.3);}
 up(e){if(!this.drag||this.animating||e.pointerId!==this.drag.id)return;this.settle(shouldComplete(this.drag.p));}
 settle(complete){if(!this.drag)return;this.animating=true;const from=this.drag.p,to=complete?1:0,start=performance.now(),duration=this.motion.matches?0:430;const tick=now=>{if(!this.drag)return;const t=duration?clamp((now-start)/duration):1;this.paint(from+(to-from)*(1-(1-t)**3));if(t<1)requestAnimationFrame(tick);else{if(complete)this.spread+=this.drag.d;const id=this.drag.id;this.drag=null;this.animating=false;this.layer.replaceChildren();this.book.classList.remove('turning');this.book.style.setProperty('--turn-shadow',0);this.draw();if(id!==undefined&&this.book.hasPointerCapture(id))this.book.releasePointerCapture(id);}};requestAnimationFrame(tick);}
 cancel(immediate=false){if(!this.drag)return;if(immediate){this.drag=null;this.animating=false;this.layer.replaceChildren();this.book.classList.remove('turning');this.draw();}else this.settle(false);}
 turn(d){if(this.animating||!this.begin(d))return;this.settle(true);}
 goTo(spread){if(this.drag||this.animating)return;this.spread=clamp(spread,0,this.count-1);this.draw();}
}
